// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crypto.proto

package org.fok.core.api.model;

public final class Crypto {
  private Crypto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccountKeyPairOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.fok.core.api.model.AccountKeyPair)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes address = 1;</code>
     */
    com.google.protobuf.ByteString getAddress();

    /**
     * <code>bytes privateKey = 2;</code>
     */
    com.google.protobuf.ByteString getPrivateKey();

    /**
     * <code>bytes publicKey = 3;</code>
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <code>string genId = 4;</code>
     */
    java.lang.String getGenId();
    /**
     * <code>string genId = 4;</code>
     */
    com.google.protobuf.ByteString
        getGenIdBytes();
  }
  /**
   * Protobuf type {@code org.fok.core.api.model.AccountKeyPair}
   */
  public  static final class AccountKeyPair extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.fok.core.api.model.AccountKeyPair)
      AccountKeyPairOrBuilder {
    // Use AccountKeyPair.newBuilder() to construct.
    private AccountKeyPair(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccountKeyPair() {
      address_ = com.google.protobuf.ByteString.EMPTY;
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      genId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AccountKeyPair(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              address_ = input.readBytes();
              break;
            }
            case 18: {

              privateKey_ = input.readBytes();
              break;
            }
            case 26: {

              publicKey_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              genId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.fok.core.api.model.Crypto.internal_static_org_fok_core_api_model_AccountKeyPair_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.fok.core.api.model.Crypto.internal_static_org_fok_core_api_model_AccountKeyPair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.fok.core.api.model.Crypto.AccountKeyPair.class, org.fok.core.api.model.Crypto.AccountKeyPair.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>bytes address = 1;</code>
     */
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    public static final int PRIVATEKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <code>bytes privateKey = 2;</code>
     */
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }

    public static final int PUBLICKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>bytes publicKey = 3;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int GENID_FIELD_NUMBER = 4;
    private volatile java.lang.Object genId_;
    /**
     * <code>string genId = 4;</code>
     */
    public java.lang.String getGenId() {
      java.lang.Object ref = genId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genId_ = s;
        return s;
      }
    }
    /**
     * <code>string genId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGenIdBytes() {
      java.lang.Object ref = genId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!address_.isEmpty()) {
        output.writeBytes(1, address_);
      }
      if (!privateKey_.isEmpty()) {
        output.writeBytes(2, privateKey_);
      }
      if (!publicKey_.isEmpty()) {
        output.writeBytes(3, publicKey_);
      }
      if (!getGenIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, genId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, address_);
      }
      if (!privateKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, privateKey_);
      }
      if (!publicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, publicKey_);
      }
      if (!getGenIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, genId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.fok.core.api.model.Crypto.AccountKeyPair)) {
        return super.equals(obj);
      }
      org.fok.core.api.model.Crypto.AccountKeyPair other = (org.fok.core.api.model.Crypto.AccountKeyPair) obj;

      boolean result = true;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getPrivateKey()
          .equals(other.getPrivateKey());
      result = result && getPublicKey()
          .equals(other.getPublicKey());
      result = result && getGenId()
          .equals(other.getGenId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PRIVATEKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey().hashCode();
      hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (37 * hash) + GENID_FIELD_NUMBER;
      hash = (53 * hash) + getGenId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.fok.core.api.model.Crypto.AccountKeyPair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.fok.core.api.model.Crypto.AccountKeyPair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.fok.core.api.model.Crypto.AccountKeyPair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.fok.core.api.model.Crypto.AccountKeyPair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.fok.core.api.model.Crypto.AccountKeyPair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.fok.core.api.model.Crypto.AccountKeyPair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.fok.core.api.model.Crypto.AccountKeyPair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.fok.core.api.model.Crypto.AccountKeyPair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.fok.core.api.model.Crypto.AccountKeyPair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.fok.core.api.model.Crypto.AccountKeyPair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.fok.core.api.model.Crypto.AccountKeyPair prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.fok.core.api.model.AccountKeyPair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.fok.core.api.model.AccountKeyPair)
        org.fok.core.api.model.Crypto.AccountKeyPairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.fok.core.api.model.Crypto.internal_static_org_fok_core_api_model_AccountKeyPair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.fok.core.api.model.Crypto.internal_static_org_fok_core_api_model_AccountKeyPair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.fok.core.api.model.Crypto.AccountKeyPair.class, org.fok.core.api.model.Crypto.AccountKeyPair.Builder.class);
      }

      // Construct using org.fok.core.api.model.Crypto.AccountKeyPair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        address_ = com.google.protobuf.ByteString.EMPTY;

        privateKey_ = com.google.protobuf.ByteString.EMPTY;

        publicKey_ = com.google.protobuf.ByteString.EMPTY;

        genId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.fok.core.api.model.Crypto.internal_static_org_fok_core_api_model_AccountKeyPair_descriptor;
      }

      public org.fok.core.api.model.Crypto.AccountKeyPair getDefaultInstanceForType() {
        return org.fok.core.api.model.Crypto.AccountKeyPair.getDefaultInstance();
      }

      public org.fok.core.api.model.Crypto.AccountKeyPair build() {
        org.fok.core.api.model.Crypto.AccountKeyPair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.fok.core.api.model.Crypto.AccountKeyPair buildPartial() {
        org.fok.core.api.model.Crypto.AccountKeyPair result = new org.fok.core.api.model.Crypto.AccountKeyPair(this);
        result.address_ = address_;
        result.privateKey_ = privateKey_;
        result.publicKey_ = publicKey_;
        result.genId_ = genId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.fok.core.api.model.Crypto.AccountKeyPair) {
          return mergeFrom((org.fok.core.api.model.Crypto.AccountKeyPair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.fok.core.api.model.Crypto.AccountKeyPair other) {
        if (other == org.fok.core.api.model.Crypto.AccountKeyPair.getDefaultInstance()) return this;
        if (other.getAddress() != com.google.protobuf.ByteString.EMPTY) {
          setAddress(other.getAddress());
        }
        if (other.getPrivateKey() != com.google.protobuf.ByteString.EMPTY) {
          setPrivateKey(other.getPrivateKey());
        }
        if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setPublicKey(other.getPublicKey());
        }
        if (!other.getGenId().isEmpty()) {
          genId_ = other.genId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.fok.core.api.model.Crypto.AccountKeyPair parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.fok.core.api.model.Crypto.AccountKeyPair) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes address = 1;</code>
       */
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>bytes address = 1;</code>
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes address = 1;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes privateKey = 2;</code>
       */
      public com.google.protobuf.ByteString getPrivateKey() {
        return privateKey_;
      }
      /**
       * <code>bytes privateKey = 2;</code>
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes privateKey = 2;</code>
       */
      public Builder clearPrivateKey() {
        
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes publicKey = 3;</code>
       */
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>bytes publicKey = 3;</code>
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes publicKey = 3;</code>
       */
      public Builder clearPublicKey() {
        
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private java.lang.Object genId_ = "";
      /**
       * <code>string genId = 4;</code>
       */
      public java.lang.String getGenId() {
        java.lang.Object ref = genId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          genId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string genId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGenIdBytes() {
        java.lang.Object ref = genId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          genId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string genId = 4;</code>
       */
      public Builder setGenId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        genId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string genId = 4;</code>
       */
      public Builder clearGenId() {
        
        genId_ = getDefaultInstance().getGenId();
        onChanged();
        return this;
      }
      /**
       * <code>string genId = 4;</code>
       */
      public Builder setGenIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        genId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.fok.core.api.model.AccountKeyPair)
    }

    // @@protoc_insertion_point(class_scope:org.fok.core.api.model.AccountKeyPair)
    private static final org.fok.core.api.model.Crypto.AccountKeyPair DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.fok.core.api.model.Crypto.AccountKeyPair();
    }

    public static org.fok.core.api.model.Crypto.AccountKeyPair getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountKeyPair>
        PARSER = new com.google.protobuf.AbstractParser<AccountKeyPair>() {
      public AccountKeyPair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AccountKeyPair(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AccountKeyPair> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountKeyPair> getParserForType() {
      return PARSER;
    }

    public org.fok.core.api.model.Crypto.AccountKeyPair getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fok_core_api_model_AccountKeyPair_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_fok_core_api_model_AccountKeyPair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014crypto.proto\022\026org.fok.core.api.model\"W" +
      "\n\016AccountKeyPair\022\017\n\007address\030\001 \001(\014\022\022\n\npri" +
      "vateKey\030\002 \001(\014\022\021\n\tpublicKey\030\003 \001(\014\022\r\n\005genI" +
      "d\030\004 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_fok_core_api_model_AccountKeyPair_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_fok_core_api_model_AccountKeyPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_fok_core_api_model_AccountKeyPair_descriptor,
        new java.lang.String[] { "Address", "PrivateKey", "PublicKey", "GenId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
